behaviors:
  Spider2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 128
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 512
        learning_rate: 0.0003
    keep_checkpoints: 20
    checkpoint_interval: 50000
    max_steps: 3000000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: True
