behaviors:
  Spider2Nav:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0004
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 30.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 30.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 128
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1500000000
    time_horizon: 1000
    threaded: true
    summary_freq: 30000
